//! This file is auto-generated by binder.
//! It embeds static assets directly into the Zig binary for runtime use
//! without external dependencies. Do not edit this file manually.
//!
//! Generated from: frontend
//! Namespace: quark_frontend

const std = @import("std");

pub const EmbeddedResource = struct {
    file: []const u8,
    path: []const u8,
};

pub const resources = [_]EmbeddedResource{
    .{ .file = "assets/Fonts/Fredoka/OFL.txt", .path = @embedFile("frontend/assets/Fonts/Fredoka/OFL.txt") },
    .{ .file = "assets/Fonts/Fredoka/Fredoka.ttf", .path = @embedFile("frontend/assets/Fonts/Fredoka/Fredoka.ttf") },
    .{ .file = "assets/Gradient.svg", .path = @embedFile("frontend/assets/Gradient.svg") },
    .{ .file = "style.css", .path = @embedFile("frontend/style.css") },
    .{ .file = "index.html", .path = @embedFile("frontend/index.html") },
};

pub fn get(name: []const u8) ?[]const u8 {
    for (resources) |resource| {
        if (std.mem.eql(u8, resource.file, name)) return resource.path;
    }
    return null;
}
