/// This file is auto-generated by Quark.
/// It embeds static frontend assets (HTML, CSS, JS, etc) directly into the Zig binary
/// for use at runtime without external dependencies. Do not edit this file.

const std = @import("std");

pub const File = struct {
    name: []const u8,
    data: []const u8,
};

pub const files = [_]File{
    .{ .name = "assets/Fonts/Fredoka/OFL.txt", .data = @embedFile("frontend/assets/Fonts/Fredoka/OFL.txt") },
    .{ .name = "assets/Fonts/Fredoka/Fredoka.ttf", .data = @embedFile("frontend/assets/Fonts/Fredoka/Fredoka.ttf") },
    .{ .name = "assets/Gradient.svg", .data = @embedFile("frontend/assets/Gradient.svg") },
    .{ .name = "style.css", .data = @embedFile("frontend/style.css") },
    .{ .name = "index.html", .data = @embedFile("frontend/index.html") },
};

pub fn get(name: []const u8) ?[]const u8 {
    for (files) |file| {
        if (std.mem.eql(u8, file.name, name)) return file.data;
    }
    return null;
}