//! This file is auto-generated by binder.
//! It embeds static assets directly into the Zig binary for runtime use
//! without external dependencies. Do not edit this file manually.
//!
//! Generated from: src_quark
//! Namespace: quark_frontend

const std = @import("std");

pub const EmbeddedResource = struct {
    file: []const u8,
    path: []const u8,
};

pub const resources = [_]EmbeddedResource{
    .{ .file = "css/bar.css", .path = @embedFile("src_quark/css/bar.css") },
    .{ .file = "css/pages.css", .path = @embedFile("src_quark/css/pages.css") },
    .{ .file = "css/main.css", .path = @embedFile("src_quark/css/main.css") },
    .{ .file = "css/ui/icons.css", .path = @embedFile("src_quark/css/ui/icons.css") },
    .{ .file = "css/ui/buttons.css", .path = @embedFile("src_quark/css/ui/buttons.css") },
    .{ .file = "css/boxicons.min.css", .path = @embedFile("src_quark/css/boxicons.min.css") },
    .{ .file = "css/themes.css", .path = @embedFile("src_quark/css/themes.css") },
    .{ .file = "fonts/boxicons.woff2", .path = @embedFile("src_quark/fonts/boxicons.woff2") },
    .{ .file = "javascript/main.js", .path = @embedFile("src_quark/javascript/main.js") },
    .{ .file = "javascript/eventListeners.js", .path = @embedFile("src_quark/javascript/eventListeners.js") },
    .{ .file = "index.html", .path = @embedFile("src_quark/index.html") },
};

pub fn get(name: []const u8) ?[]const u8 {
    for (resources) |resource| {
        if (std.mem.eql(u8, resource.file, name)) return resource.path;
    }
    return null;
}
